### ISSUE TITLE
Things the os needs

### ISSUE THREAD

**Issue by proJM1** [Avdan-OS/Website#134]
Sorry, that is not to do with the website but the [main repo](https://github.com/Avdan-OS/AvdanOS) got deleted and the [other repo](https://github.com/Avdan-OS/avdan-os-repository) doesn't allow issues.

- Screensavers!
- Hibernation
- able to run .exe/.msi

**Comment by itsakuro** [comment]
We didn't really discuss this in today's meeting but we definitely should in tomorrow's. Ability to run .exe files is a big plus so we should discuss it with the rest of the team when we have the time 👍

**Comment by proJM1** [comment]
I think that hibernation is also a very big plus. It's in windows but rarely used. Think of it as shutting down your computer but when you turn it on your apps are still there. Screensavers are just something that I love and I would like to have them.

**Comment by AZProductions** [comment]
You should move this conversation to the suggestions repo.

**Comment by proJM1** [comment]
> You should move this conversation to the suggestions repo.

Will do, thanks.
