### ISSUE TITLE
make better for the os

### ISSUE THREAD

**Issue by thebaconstudio** [Avdan-OS/Website#163]
add this for the os
1 | add resend so you can resend
2 | add a photos folder
3 | add a videos folder

**Comment by thebaconstudio** [comment]
its a enhancement

**Comment by AZProductions** [comment]
Hi, could you add more detail to this issue, I have no idea what you mean with add a video folder? Regards, Pigpot

**Comment by AZProductions** [comment]
Perhaps this is better for the issues repo, instead of the website repo

**Comment by thebaconstudio** [comment]
you can add photos to the photos folder

and the videos folder is for adding videos to it

**Comment by AZProductions** [comment]
You should ask this question in the suggestions repo, instead of the website repo. -Pigpot
