### ISSUE TITLE
Translation bug in every language options

### ISSUE THREAD

**Issue by donthaveaneme** [Avdan-OS/Website#210]
![image](https://user-images.githubusercontent.com/105922090/181918846-321285ac-6a03-4803-b36a-eb6b41546b9d.png)
The link : https://avdanos.com/features-beta
So i've pull request to fix the indonesian grammar and translation. Im glad its approved, but then when i checked, the translation wasn't fully translated with what i translated times ago. I mean it maybe a bug, and yeah it is. 

I have a screenshot with 4 language (Indonesian, Dutch, Arabic and Chinese) that the sentence below of title was not translated, and still on English language. Hope this help

**Comment by froxcey** [comment]
That's weird, the default language should be GB and seems like it got changed to US. I will patch that.
