### ISSUE TITLE
Light mode mode issue in avdanos.com

### ISSUE THREAD

**Issue by GGGaming71** [Avdan-OS/Website#221]
Dark Mode:
<img width="1505" alt="Dark" src="https://user-images.githubusercontent.com/106931950/182041279-49c7779a-0cd2-4b3a-8f25-de5ff2163c24.png">
Light Mode:
<img width="1505" alt="Light" src="https://user-images.githubusercontent.com/106931950/182041290-4e48aec5-271e-417e-a030-7181a458f697.png">

**Comment by froxcey** [comment]
This is an intentional design by Pigpot. He said the dark theme design looks better but it doesn't work with light theme.

**Comment by GGGaming71** [comment]
> This is an intentional design by Pigpot. He said the dark theme design looks better but it doesn't work with light theme.

oh ok sorry for the misunderstanding 😅
