### ISSUE TITLE
Light mode is wrong

### ISSUE THREAD

**Issue by LeOptix** [Avdan-OS/Website#361]
### Please select the browsers that you have tested this issue on.

- [ ] Safari, any iOS browser (Webkit)
- [ ] Firefox, Tor (Gecko+Quantum)
- [X] Chrome, Brave, Edge, Opera (Chromium)

### Please make sure your browsers is maintained and up to date

- [X] Yes, my browser is maintained and up to date

### Please select the operating system that you have tested this issue on.

- [ ] Linux based (Debian, Ubuntu, Arch, Fedora etc.)
- [ ] MacOS
- [X] Windows

### Please put your hardware/model information here.

AMD Radeon A9-9425 R5 (2 CPU Cores + 3 Integrated GPU Cores)
3.40 GB of usable RAM
117 GB NTFS SSD
Windows 10 22H2
UEFI BIOS 2.0
TPM
_Device model:_ `Lenovo Ideapad 330S`

### Please explain what went wrong.

When light mode is enabled, the website just brakes. The effects & blurs are inverted, making imposible to see the top. Even the features animation is inverted. Some texts aren't legibe, and in general light mode is _too light_.

### Please list pages that this issue is related to.

- Home
- Features

### What do you think could be the potential cause of the issue?

Other

### Please make sure this issue is not a duplicate of an existing issue.

- [X] Yes, I have search for this issue on this repository and none were found

**Comment by Froxcey** [comment]
Any screenshots? Please also provide me with details on what exact should be changed. It could really help me with improving the light mode design.

**Comment by Froxcey** [comment]
lol
I develop on dark mode, so honestly not my problem i guess ¯\\\_| ಠ ∧ ಠ |_/¯
