### ISSUE TITLE
Feature Request - Update the tab bar.

### ISSUE THREAD

**Issue by LeOptix** [Avdan-OS/Website#363]
**Is your feature request related to a problem? Please describe.**
Seeing that the browser tab has the old logo, a slogan that you can't even read and that isn't anywhere else on the website, and that it doesn't change the text when on other pages, feels _uncomfortable_ somehow. (By the way, why do GitHub and the website have different slogans?)

**Describe the solution you'd like**
Update the browser tab icon, change the text and make it adapt to the page where you are (and the language too.) And move the slogan to somewhere where it is readable.

**Describe alternatives you've considered**
n/A

**Additional context**
n/A

**Comment by Froxcey** [comment]
Should be fixed. If you don't see the update, clear your cache or try using a private/anonymous tab.

![vibe](https://user-images.githubusercontent.com/51555391/176177206-ec3f9dce-8780-4fe8-b6ac-5eeeac2038d4.gif)
