### ISSUE TITLE
Feature Request - Remove the web demo completely.

### ISSUE THREAD

**Issue by LeOptix** [Avdan-OS/Website#364]
**Is your feature request related to a problem? Please describe.**
The web demo is _discontinued_, or it was supposed to be. In fact, spending time developing a simple web demo isn't worth it. So, this is a reason to discontinue it and remove it completely from the web and from the GitHub. But what makes no sense is that it was already supposed to be _discontinued_, but it's still alive. And other thing that makes no sense is having the demo in the Downloads page. **Even if it wasn't ended**, it's actually strange to have a web demo into the downloads page, because it isn't a download and it also has its own tab in the nav menu.

**Describe the solution you'd like**
Completely removing the web demo, from the web and from the GitHub.

**Describe alternatives you've considered**
n/A

**Additional context**
n/A

**Comment by SunightMC** [comment]
I personally think that just replacing the old web demo by the one CodeHeister made would be sufficient.
